// Configure Supabase in site-config.js and run sql/reviews.sql before enabling reviews.
export async function setupComments(appId){
const $=id=>document.getElementById(id),cfg=window.SITE_CONFIG||{},notice=$('review-setup-notice'),emailForm=$('email-form'),reviewForm=$('review-form'),feedback=$('review-feedback'),list=$('review-list');
if(!/^https:\/\/[^\s]+\.supabase\.co\/?$/.test(cfg.supabaseUrl||'')||!cfg.supabasePublishableKey){notice.textContent='ثبت نظر پس از اتصال Supabase فعال می‌شود؛ در حال حاضر نظری دریافت نمی‌شود.';return}
let supabase,user=null;
try{const m=await import('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm');supabase=m.createClient(cfg.supabaseUrl,cfg.supabasePublishableKey)}catch{notice.textContent='سرویس نظرات در دسترس نیست.';return}
notice.hidden=true;
async function auth(){const {data}=await supabase.auth.getUser();user=data.user;emailForm.hidden=!!user;reviewForm.hidden=!user;$('auth-state').hidden=!user;if(user){const out=document.createElement('button');out.type='button';out.textContent='خروج';out.className='logout-button';out.addEventListener('click',async()=>{await supabase.auth.signOut();await auth()});$('auth-state').replaceChildren(document.createTextNode('ورود با '+(user.email||'ایمیل')),out)}}
async function reviews(){const {data,error}=await supabase.from('app_reviews').select('display_name,rating,body,created_at,status,author_id').eq('app_slug',appId).order('created_at',{ascending:false}).limit(100);if(error){list.textContent='دریافت نظرات ممکن نشد.';return}
const approved=(data||[]).filter(r=>r.status==='approved'),mine=(data||[]).filter(r=>r.status==='pending'&&user&&r.author_id===user.id);list.replaceChildren();
const n=approved.length;$('review-count').textContent=n?n.toLocaleString('fa-IR')+' نظر تأییدشده':'';
const rating=n?approved.reduce((s,r)=>s+r.rating,0)/n:0,summary=n?'★ '+rating.toLocaleString('fa-IR',{minimumFractionDigits:1,maximumFractionDigits:1})+' از ۵ · '+n.toLocaleString('fa-IR')+' نظر':'☆ هنوز نظری ثبت نشده است.';$('review-summary').textContent=summary;$('detail-rating').textContent=summary;
for(const r of [...mine,...approved]){const article=document.createElement('article'),head=document.createElement('div'),name=document.createElement('strong'),stars=document.createElement('span'),body=document.createElement('p');article.className='review-item';head.className='review-item-head';name.textContent=r.display_name;stars.textContent='★'.repeat(r.rating)+'☆'.repeat(5-r.rating);stars.className='review-stars';body.textContent=r.body;head.append(name,stars);article.append(head);if(r.status==='pending'){const b=document.createElement('span');b.className='pending-badge';b.textContent='در انتظار تأیید';article.append(b)}article.append(body);list.append(article)}
if(!n&&!mine.length){const p=document.createElement('p');p.className='review-empty';p.textContent='هنوز نظری ثبت نشده است.';list.append(p)}}
emailForm.addEventListener('submit',async e=>{e.preventDefault();const btn=emailForm.querySelector('button');btn.disabled=true;feedback.textContent='در حال ارسال…';const {error}=await supabase.auth.signInWithOtp({email:$('login-email').value.trim(),options:{emailRedirectTo:location.href}});feedback.textContent=error?'ارسال لینک ناموفق بود: '+error.message:'لینک ورود به ایمیلت فرستاده شد.';btn.disabled=false});
reviewForm.addEventListener('submit',async e=>{e.preventDefault();if(!user)return;const display_name=$('review-name').value.trim(),rating=Number($('review-rating').value),body=$('review-body').value.trim();if(display_name.length<2||display_name.length>60||body.length<10||body.length>2000||rating<1||rating>5){feedback.textContent='نام، امتیاز و متن را درست وارد کن.';return}const btn=reviewForm.querySelector('button');btn.disabled=true;const {error}=await supabase.from('app_reviews').insert({app_slug:appId,author_id:user.id,display_name,rating,body,status:'pending'});btn.disabled=false;feedback.textContent=error?(error.code==='23505'?'برای این برنامه قبلاً نظر ثبت کرده‌ای.':error.message):'نظر ثبت شد و پس از بررسی نمایش داده می‌شود.';if(!error){reviewForm.reset();await reviews()}});
await auth();await reviews();supabase.auth.onAuthStateChange(()=>{setTimeout(async()=>{await auth();await reviews()},0)});
}